### ISSUE TITLE
Buttons within the extension do not work in Chrome

### ISSUE THREAD

**Issue by MrSuttonmann** [jackdomleo7/Checka11y.css-browser-extension#1]
![image](https://user-images.githubusercontent.com/7480500/104709971-6e389b80-5717-11eb-9595-a7cc6f7d1594.png)

Your Docs, Donate and Github buttons do not work in the Chrome extension.

Chrome Version: 87.0.4280.141
Extension version: 1.0.0

**Comment by jackdomleo7** [comment]
Thank you for raising!! That's very odd, it did work when I tested it. I'll take a look. 🙂

**Comment by jackdomleo7** [comment]
Thanks for raising this @MrSuttonmann! 🙏 This will be released in v1.1.0, which will automatically update when I publish v1.1.0 to Chrome & Firefox.

**Comment by MrSuttonmann** [comment]
Thank you @jackdomleo7
