### ISSUE TITLE
Investigate (& maybe implement) upgrade to manifest v3

### ISSUE THREAD

**Issue by jackdomleo7** [jackdomleo7/Checka11y.css-browser-extension#11]
Mozilla & Google have released v3 of their addon/extension manifest. It would be good to see what exactly needs doing to this repo to make it compatible on v3 for both Chrome & Firefox.

https://blog.mozilla.org/addons/2021/05/27/manifest-v3-update

Goal is to maintain cross-browser support for this extension. Currently, Checka11y.css browser extension is compatible on both Firefox & Chrome using the same code (not all extensions can do this and they have to create 2 separate repos for each browser) - we want to try and maintain this if we can so there is less code to maintain.

**Comment by tannerdolby** [comment]
If this is a Chrome extension (which I think it is from the file structure with code for the popup UI etc), I'm happy to be assigned this and migrate things to MV3. I've recently been spending alot of time on [developer.chrome.com](https://github.com/GoogleChrome/developer.chrome.com) studying extension development (and doing open source stuff) so most of the MV3 migration guide is still really fresh.

Nice job on breaking this out into an extension. While working on the stylesheet project (Checka11y.css) I thought how useful this would be as a chrome extension so kudos!

**Comment by jackdomleo7** [comment]
Yeah it was a nice project to work on.

This project is the source code for both the Firefox Addon and Chrome Extension, which just so happens to be the same code. Hence why some investigation into the upgrade to v3 of the manifest is in order to see whether this project can still be for Firefox & Chrome or if it needs splitting out. 🙂

**Comment by tannerdolby** [comment]
Ah ok I see. I'm not too familiar with how the Firefox Addons work so that will be the first place I do investigating. I'm comfortable migrating chrome extensions from MV2 to MV3. But I agree, we can determine if splitting it into two will be necessary and then go from there.
